{
 "title": "Usage Visualization - Sessions",
 "tags": [ "Citrix-uberAgent" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Subscription",
    "query": {}
   },
   {
    "name": "Workspace",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Citrix session overview",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "uberAgent_CitrixSession_SessionConfig_CL\r\n| summarize\r\n    UniqueHosts = dcount(Computer),\r\n    UniqueUsers = dcount(SessionUser_s),\r\n    UniqueSessions = dcount(SessionGUID_g)\r\n\r\n    \r\n",
      "resources": [ "$Workspace" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Network policies",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "uberAgent_CitrixSession_SessionConfig_CL\r\n| summarize \r\n    [\"Policy Session reliability connections\"] = arg_max(NetworkPolicyAcceptSessionReliabilityConnections_b,TimeGenerated),\r\n    [\"Policy Session reliability port\"] = arg_max(NetworkPolicySessionReliabilityPort_d, TimeGenerated),\r\n    [\"Policy Session reliability timeout (s)\"] = arg_max(NetworkPolicySessionReliabilityTimeout_d, TimeGenerated),\r\n    [\"Policy ICA listener port\"] = arg_max(NetworkPolicyICAListenerPortNumber_d, TimeGenerated)\r\n    by SessionGUID_g\r\n| mv-expand PolicyValues = pack_array(\r\n    pack(\"Policy\", \"Policy Session reliability connections\", \"Value\", [\"Policy Session reliability connections\"]),\r\n    pack(\"Policy\", \"Policy Session reliability port\", \"Value\", [\"Policy Session reliability port\"]),\r\n    pack(\"Policy\", \"Policy Session reliability timeout (s)\", \"Value\", [\"Policy Session reliability timeout (s)\"]),\r\n    pack(\"Policy\", \"Policy ICA listener port\", \"Value\", [\"Policy ICA listener port\"])\r\n)\r\n| extend Policy = tostring(PolicyValues[\"Policy\"]), Value = tostring(PolicyValues[\"Value\"])\r\n| summarize Count = count() by Policy, Value\r\n| extend Value = replace_string(Value, \"true\", \"Allowed\") \r\n| extend Value = split(Value, \".\")\r\n| extend [\"Value(s): #sessions\"] = strcat(Value[0], \": \", Count)\r\n| summarize [\"Value(s): #sessions\"] = make_list([\"Value(s): #sessions\"]) by Policy\r\n| mv-expand [\"Value(s): #sessions\"]\r\n| project Policy, [\"Value(s): #sessions\"]\r\n| order by Policy asc\r\n",
      "resources": [ "$Workspace" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Transport protocols",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "uberAgent_Session_SessionDetail_CL\r\n| where isnotempty(SessionTransportProtocols_s)\r\n| summarize SessionTransportProtocolsLatest = arg_max(TimeGenerated, SessionTransportProtocols_s) by SessionGUID_g\r\n| summarize count() by SessionTransportProtocols_s \r\n",
      "resources": [ "$Workspace" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Sessions connected via",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "uberAgent_CitrixSession_SessionConfig_CL\r\n| summarize NetworkConnectedViaLatest = arg_max(TimeGenerated, NetworkConnectedVia_s) by SessionGUID_g\r\n| summarize count() by NetworkConnectedVia_s ",
      "resources": [ "$Workspace" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Enlightened Data Transport MTU size",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "uberAgent_CitrixSession_SessionConfig_CL\r\n| where isnotempty(NetworkEdtMtu_d)\r\n| summarize NetworkEdtMtuLatest = arg_max(TimeGenerated, NetworkEdtMtu_d) by SessionGUID_g\r\n| summarize count() by NetworkEdtMtu_d \r\n| project countEntries = count_, NetworkEdtMtu = tostring(toint(NetworkEdtMtu_d))",
      "resources": [ "$Workspace" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  { "title": "Session access", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Client component by platform (top 10)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "uberAgent_Session_SessionDetail_CL\r\n| where isnotempty(SessionClientVersion_s) and SessionBrokerType_s in (\"Citrix\")\r\n| summarize count() by SessionClientVersion_s, SessionClientPlatform_s, SessionGUID_g\r\n| project VersionString = SessionClientPlatform_s\r\n| summarize Count = count() by VersionString\r\n| sort by Count\r\n| limit 10 \r\n",
      "resources": [ "$Workspace" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Client component by version (top 10)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "uberAgent_Session_SessionDetail_CL\r\n| where isnotempty(SessionClientVersion_s) and SessionBrokerType_s in (\"Citrix\")\r\n| summarize count() by SessionClientVersion_s, SessionClientPlatform_s, SessionGUID_g\r\n| project VersionString = SessionClientVersion_s\r\n| summarize Count = count() by VersionString\r\n| sort by Count\r\n| limit 10 \r\n",
      "resources": [ "$Workspace" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Client component platform@version (top 10)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "uberAgent_Session_SessionDetail_CL\r\n| where isnotempty(SessionClientVersion_s) and SessionBrokerType_s in (\"Citrix\")\r\n| summarize count() by SessionClientVersion_s, SessionClientPlatform_s, SessionGUID_g\r\n| project VersionString = strcat(SessionClientPlatform_s, '@', SessionClientVersion_s)\r\n| summarize Count = count() by VersionString\r\n| sort by Count\r\n| limit 10 \r\n",
      "resources": [ "$Workspace" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Connection state distribution (Sessions)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "uberAgent_Session_SessionDetail_CL\r\n| where isnotempty(SessionConnectionState_s) \r\n| summarize SessionConnectionStateLatest = arg_max(TimeGenerated, SessionConnectionState_s) by SessionGUID_g\r\n| summarize count(SessionGUID_g) by SessionConnectionState_s;",
      "resources": [ "$Workspace" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Connection state distribution (Published Apps)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "uberAgent_Session_SessionDetail_CL\r\n| where isnotempty(SessionConnectionState_s) \r\n| summarize SessionConnectionStateLatest = arg_max(TimeGenerated, SessionConnectionState_s) by SessionPublishedAppsCtx_s\r\n| summarize count(SessionPublishedAppsCtx_s) by SessionConnectionState_s;",
      "resources": [ "$Workspace" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Published names used to launch sessions (top 10)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "let TotalCount = toscalar(\r\n    uberAgent_Session_SessionDetail_CL\r\n    | where isnotempty(SessionClientVersion_s) and SessionBrokerType_s in (\"Citrix\")\r\n    | summarize SessionPublishedNameLatest = arg_max(TimeGenerated, SessionPublishedName_s) by SessionGUID_g\r\n    | summarize Count = count() by SessionPublishedName_s\r\n    | sort by Count\r\n    | limit 10\r\n    | summarize sum(Count)\r\n);\r\n\r\n\r\nuberAgent_Session_SessionDetail_CL\r\n| where isnotempty(SessionClientVersion_s) and SessionBrokerType_s in (\"Citrix\")\r\n| summarize SessionPublishedNameLatest = arg_max(TimeGenerated, SessionPublishedName_s) by SessionGUID_g\r\n| summarize Count = count() by SessionPublishedName_s\r\n| sort by Count\r\n| limit 10\r\n| extend TotalCount\r\n| extend [\"Published Name (%)\"] = round(Count * 100.0 / TotalCount, 1)\r\n| project-away Count, TotalCount\r\n",
      "resources": [ "$Workspace" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Published application usage (top 10)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "uberAgent_Session_SessionDetail_CL\r\n| where SessionBrokerType_s == \"Citrix\" and SessionPublishedAppsCtx_s !=\"\"\r\n| summarize dcount(SessionGUID_g) by SessionPublishedAppsCtx_s\r\n| project [\"Published App Name\"] = SessionPublishedAppsCtx_s, [\"Session Count\"] = dcount_SessionGUID_g\r\n| sort by ['Session Count'] desc\r\n| limit 10",
      "resources": [ "$Workspace" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Data table",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "uberAgent_CitrixSession_SessionConfig_CL\r\n| join (uberAgent_Session_SessionDetail_CL) on SessionGUID_g\r\n| summarize \r\narg_max(TimeGenerated,Computer),\r\narg_max(TimeGenerated, AudioActualPriority_s),\r\narg_max(TimeGenerated,AudioPolicyAllowMicrophoneRedirection_b),\r\narg_max(TimeGenerated,AudioPolicyAllowRedirection_b),\r\narg_max(TimeGenerated,AudioPolicyPriority_s),\r\narg_max(TimeGenerated,AudioPolicySoundQuality_s),\r\narg_max(TimeGenerated,CdmActualPriority_s),\r\narg_max(TimeGenerated,CdmPolicyAllowDriveRedirection_b),\r\narg_max(TimeGenerated,CdmPolicyReadOnly_b),\r\narg_max(TimeGenerated,CdmPolicyPriority_s),\r\narg_max(TimeGenerated,CdmVolumes_s),\r\narg_max(TimeGenerated,DisplayMode_d),\r\narg_max(TimeGenerated,ThinwirePolicyFps_d),\r\narg_max(TimeGenerated,ThinwirePolicyPriority_s),\r\narg_max(TimeGenerated,ThinwirePolicyUseHardwareEncoding_b),\r\narg_max(TimeGenerated,ThinwirePolicyUseVideoCodec_s),\r\narg_max(TimeGenerated,ThinwirePolicyVisualQuality_s),\r\narg_max(TimeGenerated,ThinwireActualPriority_s),\r\narg_max(TimeGenerated,ThinwireColorDepth_d),\r\narg_max(TimeGenerated,ThinwireComponentEncoder_s),\r\narg_max(TimeGenerated,ThinwireHardwareEncodeInUse_b),\r\narg_max(TimeGenerated,ThinwireVideoCodecType_s),\r\narg_max(TimeGenerated,ThinwireColorspace_s),\r\narg_max(TimeGenerated,ThinwireVideoCodecUse_s),\r\narg_max(TimeGenerated,NetworkPolicyAcceptSessionReliabilityConnections_b),\r\narg_max(TimeGenerated,NetworkPolicySessionReliabilityPort_d),\r\narg_max(TimeGenerated,NetworkPolicySessionReliabilityTimeout_d),\r\narg_max(TimeGenerated,NetworkPolicyICAListenerPortNumber_d),\r\narg_max(TimeGenerated,NetworkEdtMtu_d),\r\narg_max(TimeGenerated,NetworkConnectedVia_s),\r\narg_max(TimeGenerated,PrinterActualPriority_s),\r\narg_max(TimeGenerated,PrinterPolicyAllowRedirection_b),\r\narg_max(TimeGenerated, PrinterPolicyAutoCreateClientPrinters_d),\r\narg_max(TimeGenerated,PrinterPolicyPriority_s),\r\narg_max(TimeGenerated,PrinterSessionPrinter_s),\r\narg_max(TimeGenerated,USBActualPriority_s),\r\narg_max(TimeGenerated,USBPolicyAllowPNPRedirection_b),\r\narg_max(TimeGenerated,USBPolicyAllowUSBSupport_b),\r\narg_max(TimeGenerated,USBPolicyPriority_s),\r\narg_max(TimeGenerated,SessionUser_s),\r\narg_max(TimeGenerated,SessionFgBrowserActiveTabHost_s),\r\narg_max(TimeGenerated,TimeGenerated),\r\narg_max(TimeGenerated,SessionConnectionState_s),\r\narg_max(TimeGenerated,SessionTransportProtocols_s),\r\narg_max(TimeGenerated,SessionLogonTime_s),\r\nmake_set(SessionClientIp_s,10),\r\nmake_set(SessionClientPlatform_s,10),\r\nmake_set(SessionClientVersion_s,10),\r\nmake_set(SessionPublishedName_s,10),\r\nmake_set(SessionPublishedAppsCtx_s,10),\r\nmake_set(SessionEncryptionCtx_s,10)\r\nby SessionGUID_g\r\n| project \r\n[\"User\"] = replace_string(SessionUser_s, \"\\\\\", \"\\\\\\\\\"),\r\n[\"UserCase\"] = replace_string(SessionUser_s, \"\\\\\", \"\\\\\\\\\"),\r\n[\"Host\"] = Computer,\r\n[\"Session Logon Time\"] = SessionLogonTime_s,\r\n[\"LastSeen\"] = TimeGenerated,\r\n[\"Last state\"] = SessionConnectionState_s,\r\n[\"Display mode\" ] = DisplayMode_d,\r\n[\"Transport protocols\"] = SessionTransportProtocols_s,\r\n[\"EDT MTU\"] = NetworkEdtMtu_d,\r\n[\"Connected via\"] = NetworkConnectedVia_s,\r\nSessionGUID_g\r\n| project-away UserCase\r\n\r\n",
      "resources": [ "$Workspace" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  }
 ]
}