{
 "title": "Usage Visualization - Apps",
 "tags": [ "Citrix-uberAgent" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Subscription",
    "query": {}
   },
   {
    "name": "Workspace",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "uberAgent_Process_ProcessDetail_CL\r\n| where SessionID_d  > 0\r\n| where isnotempty(AppId_s)\r\n| where AppId_s !contains \"OS\" \r\n| summarize \r\n    AppNameCount = dcount(AppId_s),\r\n    VersionCount = dcount(AppVersion_s),\r\n    UserCount = dcount(ProcUser_s),\r\n    HostCount = dcount(Computer)",
      "resources": [ "$Workspace" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Foreground application over time (%)",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "uberAgent_Session_SessionDetail_CL\r\n| summarize Count = count() by bin(TimeGenerated, 30m), SessionFgAppId_s \r\n| evaluate pivot(SessionFgAppId_s, sum(Count))\r\n| extend PackedColumns = pack_all()\r\n| extend RowTotal = 0\r\n| mv-apply PackedColumns on (\r\n    extend KeyValue = todynamic(PackedColumns)\r\n    | mv-expand KeyValue\r\n    | extend Key = tostring(bag_keys(KeyValue)[0]), Value = todouble(KeyValue[tostring(bag_keys(KeyValue)[0])])\r\n    | where Key != \"TimeGenerated\" and isnotnull(Value)\r\n    | summarize RowTotal = sum(Value)\r\n)\r\n| extend Percentages = pack_all()\r\n| mv-apply Percentages on (\r\n    extend KeyValue = todynamic(Percentages)\r\n    | mv-expand KeyValue\r\n    | extend Key = tostring(bag_keys(KeyValue)[0]), Value = todouble(KeyValue[tostring(bag_keys(KeyValue)[0])])\r\n    | where Key != \"TimeGenerated\" and Key != \"RowTotal\" and isnotnull(Value)\r\n    | extend Percentage = round(Value * 100.0 / RowTotal, 1)\r\n    | summarize make_bag(pack(Key, Percentage))\r\n)\r\n| evaluate bag_unpack(bag_, \"Percent_\")\r\n| project-keep TimeGenerated, Percent*\r\n| project-away Percent__Empty\r\n| extend PackedColumns = pack_all()\r\n| extend RowTotal = 0\r\n| mv-apply PackedColumns on (\r\n    extend KeyValue = todynamic(PackedColumns)\r\n    | mv-expand KeyValue\r\n    | extend Key = tostring(bag_keys(KeyValue)[0]), Value = todouble(KeyValue[tostring(bag_keys(KeyValue)[0])])\r\n    | where Key != \"TimeGenerated\" and isnotnull(Value)\r\n    | summarize RowTotal = sum(Value)\r\n)\r\n| extend Percentages = pack_all()\r\n| mv-apply Percentages on (\r\n    extend KeyValue = todynamic(Percentages)\r\n    | mv-expand KeyValue\r\n    | extend Key = tostring(bag_keys(KeyValue)[0]), Value = todouble(KeyValue[tostring(bag_keys(KeyValue)[0])])\r\n    | where Key != \"TimeGenerated\" and Key != \"RowTotal\" and isnotnull(Value)\r\n    | extend Percentage = round(Value * 100.0 / RowTotal, 1)\r\n    | summarize make_bag(pack(Key, Percentage))\r\n)\r\n| evaluate bag_unpack(bag_, \"_\")\r\n| project-keep TimeGenerated, _Percent*\r\n| sort by TimeGenerated asc ",
      "resources": [ "$Workspace" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Foreground application (top 10)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "\r\nlet TotalCount = toscalar(\r\n    uberAgent_Session_SessionDetail_CL\r\n    | where isnotempty(SessionFgAppId_s)\r\n    | summarize TotalCount = count()\r\n);\r\nuberAgent_Session_SessionDetail_CL\r\n| where isnotempty( SessionFgAppId_s)\r\n| summarize CountSessionFgAppName = count() by SessionFgAppId_s\r\n| extend [\"App in foreground (%)\"] = round(CountSessionFgAppName * 100.0 / TotalCount, 1)\r\n| project SessionFgAppId_s, [\"App in foreground (%)\"]\r\n| order by [\"App in foreground (%)\"] desc\r\n| top 10 by [\"App in foreground (%)\"]",
      "resources": [ "$Workspace" ],
      "resultFormat": "table",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Foreground process (top 10)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "\r\nlet TotalCount = toscalar(\r\n    uberAgent_Session_SessionDetail_CL\r\n    | where isnotempty(SessionFgProcessName_s)\r\n    | summarize TotalCount = count()\r\n);\r\nuberAgent_Session_SessionDetail_CL\r\n| where isnotempty(SessionFgProcessName_s)\r\n| summarize CountSessionFgProcessName = count() by SessionFgProcessName_s\r\n| extend [\"Process in foreground (%)\"] = round(CountSessionFgProcessName * 100.0 / TotalCount, 1)\r\n| project SessionFgProcessName_s, [\"Process in foreground (%)\"]\r\n| order by [\"Process in foreground (%)\"] desc\r\n| top 10 by [\"Process in foreground (%)\"]",
      "resources": [ "$Workspace" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Number of users running an application (top 10)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "uberAgent_Process_ProcessDetail_CL\r\n| where SessionID_d > 0\r\n| where isnotempty(AppId_s)\r\n| where AppId_s !contains \"OS\"\r\n| summarize [\"#Users\"] = dcount(ProcUser_s) by AppId_s\r\n| order by [\"#Users\"] desc\r\n| top 10 by [\"#Users\"]\r\n| project Name = AppId_s, [\"#Users\"]",
      "resources": [ "$Workspace" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Number of computers running an application (top 10)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "uberAgent_Process_ProcessDetail_CL\r\n| where SessionID_d > 0\r\n| where isnotempty(AppId_s)\r\n| where AppId_s !contains \"OS\"\r\n| summarize [\"#Hosts\"] = dcount(Computer) by AppId_s\r\n| order by [\"#Hosts\"] desc\r\n| top 10 by [\"#Hosts\"]\r\n| project Name = AppId_s, [\"#Hosts\"]",
      "resources": [ "$Workspace" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  },
  {
   "title": "Application usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "uberAgent_Process_ProcessDetail_CL\r\n| where SessionID_d > 0\r\n| where isnotempty(AppId_s)\r\n| where AppId_s !contains \"OS\"  \r\n| summarize [\"#Versions\"] = dcount(AppVersion_s), [\"#Users\"] = dcount(ProcUser_s), [\"#Hosts\"] = dcount(Computer) by AppId_s\r\n| extend sortfield = tolower(AppId_s)\r\n| order by sortfield asc\r\n| project Name = AppId_s, [\"#Versions\"], [\"#Users\"], [\"#Hosts\"]",
      "resources": [ "$Workspace" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     }
    }
   ]
  }
 ]
}